- name: Create actualbudget directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    group: '{{ services_user }}'    
    owner: '{{ services_user }}'    
  loop:
    - '{{ actualbudget_config_dir }}'

- name: docker-compose.yml is present
  copy:
    src: docker-compose.yml
    dest: '{{ actualbudget_config_dir }}/docker-compose.yml'
    group: '{{ services_user }}'    
    owner: '{{ services_user }}'    

- name: Actual budget Docker compose Service is up
  community.docker.docker_compose:
    project_src: '{{ actualbudget_config_dir }}'
    pull: yes
    remove_orphans: yes

- name: Deploy services using Docker Compose
  community.docker.docker_compose:
    project_src: '{{ actualbudget_config_dir }}'
    state: present
