version: "3"
services:
  uptime-kuma:
    container_name: uptime
    image: louislam/uptime-kuma:1
    environment:
      PGID: 1000
      PUID: 1000
    volumes:
      - ./data:/app/data
    ports:
      - 3001
    restart: unless-stopped
    networks:
      - ddome

networks:
    ddome: 
        external: true


