- hosts: home_servers
  become: yes
  vars_files:
    - vars.yml
  roles:
   - server_setup
   - docker_media-station
   - docker_uptime-kuma
   - docker_changedetection
   - docker_miniflux
   - docker_linkding
   - docker_home-assistant
   - docker_n8n
   - docker_silverbullet
   - docker_filestash
   - docker_homepage
   - docker_caddy-proxy
