- hosts: home_servers
  become: yes
  vars_files:
    - vars.yml
  roles:
    - mount_nas_drives
    - samba_share
    - docker_installation
    - docker_media-station
    - docker_pihole
    - docker_uptime-kuma
      # - firewall_configuration
