- hosts: home_servers
  become: yes
  vars_files:
    - vars.yml
  roles:
    - mount_nas_drives
    - samba_share
    - firewall_configuration
    - docker_installation
    - docker_vpn-tunnel
    - docker_media-station
