- name: Deploy Home Assistant
  ansible.builtin.import_tasks: "{{ playbook_dir }}/roles/shared/tasks/docker_compose_service.yml"
  vars:
    service_name: "homeassistant"
    service_extra_directories:
      - "{{ service_config_dir }}/config"
    service_extra_files:
      - src: "{{ role_path }}/files/configuration.yaml"
        dest: "config/configuration.yaml"
        mode: "0644"
