- name: Install Samba
  apt:
    name: samba
    state: present
  become: yes

- name: Create Samba user
  command: smbpasswd -a {{ samba_user }}
  become: yes
  args:
    creates: "/var/lib/samba/private/passdb.tdb"

- name: Set Samba user password
  shell: |
    smbpasswd -s -a {{ samba_user }} <<EOF
    {{ samba_password }}
    {{ samba_password }}
    EOF
  become: yes
  args:
    executable: /bin/bash

- name: Ensure shared directory exists
  file:
    path: /mnt/nas/bart
    state: directory
    mode: '0755'
    owner: '{{ samba_user }}'
    group: '{{ samba_user }}'
  become: yes

- name: Configure Samba share
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
  notify: restart samba
  become: yes

