- name: Create restic directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    group: '{{ services_user }}'    
    owner: '{{ services_user }}'    
  loop:
    - '{{ restic_service_dir }}'

- name: docker-compose.yml is present
  template:
    src: docker-compose.yml.j2
    dest: '{{ restic_service_dir }}/docker-compose.yml'
    group: '{{ services_user }}'    
    owner: '{{ services_user }}'    