- name: Install btrfs utilities
  apt:
    name: btrfs-progs
    state: present

- name: Create mount point
  file:
    path: /mnt/nas
    state: directory
    mode: '0755'

- name: Mount Btrfs RAID 1 filesystem
  mount:
    path: '{{ nas_drive }}'
    src: "{{ drives[0] }}"
    fstype: btrfs
    opts: defaults
    state: mounted
