- name: Deploy Miniflux
  ansible.builtin.import_tasks: "{{ playbook_dir }}/roles/shared/tasks/docker_compose_service.yml"
  vars:
    service_name: "miniflux"
    postgress_password: "{{ miniflux_postgres_password }}"
    admin_username: "{{ miniflux_admin_username }}"
    admin_password: "{{ miniflux_admin_password }}"