version: '3'
services:
  actualbudget:
    container_name: actualbudget
    image: docker.io/actualbudget/actual-server:latest
    volumes:
      - ./data:/data
    restart: unless-stopped
    networks:
      - ddome

networks:
    ddome: 
        external: true


