- name: Create caddy directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    group: '{{ services_user }}'    
    owner: '{{ services_user }}'    
  loop:
    - '{{ caddy_config_dir }}'

- name: Copy Caddyfile
  template:
    src: Caddyfile.j2
    dest: '{{ caddy_config_dir }}/Caddyfile'
    group: '{{ services_user }}'    
    owner: '{{ services_user }}'    

- name: docker-compose.yml is present
  template:
    src: docker-compose.yml.j2
    dest: '{{ caddy_config_dir }}/docker-compose.yml'
    group: '{{ services_user }}'    
    owner: '{{ services_user }}'    

- name: Caddy Proxy Service is up
  community.docker.docker_compose:
    project_src: '{{ caddy_config_dir }}'
    pull: yes
    remove_orphans: yes

- name: Deploy services using Docker Compose
  community.docker.docker_compose:
    project_src: '{{ caddy_config_dir }}'
    state: present
