- name: Deploy Caddy
  ansible.builtin.import_tasks: "{{ playbook_dir }}/roles/shared/tasks/docker_compose_service.yml"
  vars:
    service_name: "caddy"
    service_extra_templates:
      - src: "{{ role_path }}/templates/Caddyfile.j2"
        dest: "Caddyfile"
        mode: "0644"
    cloudflare_secret: "{{ cloudflare_access_token }}"