- name: Create linkding directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    group: '{{ services_user }}'    
    owner: '{{ services_user }}'    
  loop:
    - '{{ linkding_config_dir }}'

- name: docker-compose.yml is present
  template:
    src: docker-compose.yml.j2
    dest: '{{ linkding_config_dir }}/docker-compose.yml'
    group: '{{ services_user }}'    
    owner: '{{ services_user }}'    

- name: Linkding Docker compose Service is up
  community.docker.docker_compose:
    project_src: '{{ linkding_config_dir }}'
    pull: yes
    remove_orphans: yes

- name: Deploy services using Docker Compose
  community.docker.docker_compose:
    project_src: '{{ linkding_config_dir }}'
    state: present
