- name: Deploy Linkding 
  ansible.builtin.import_tasks: "{{ playbook_dir }}/roles/shared/tasks/docker_compose_service.yml"
  vars:
    service_name: "linkding"
    username: "{{ linkding_username }}"
    password: "{{ linkding_password }}"